name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Custom options
          plugin_notable: yes

          plugin_contributors: yes
          plugin_contributors_sections: categories
          plugin_contributors_categories: |
            {
            "📚 Documentation": ["README.md", "docs/**"],
            "💻 Code": ["source/**", "src/**", "README.md", "**/README.md", "**/metadata.yml"],
            "🐍 Build": ["pyproject.toml", "setup.py"],
            "#️⃣ Others": ["*"]
            }

          plugin_gists: yes
